services:
  test_task-app:
    build: ./
    container_name: todo-app
    command: ./wait-for-postgres.sh db ./todo-app
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - REPO_PASSWORD=qwerty
    env_file:
          - .env

  db:
    image: postgres:17
    container_name: todo-db
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=subscriptions
      - POSTGRES_USER=postgres
    ports:
      - "5435:5432"
